import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';

import '../models/optimization_report.dart';

enum ReportImageFormat { summary, full }

class GeneratedReportImage {
  const GeneratedReportImage({required this.bytes, required this.path, required this.format});
  final Uint8List bytes;
  final String path;
  final ReportImageFormat format;
}

class ReportImageService {
  static const _bg = Color(0xFF070A12);
  static const _panel = Color(0xFF111625);
  static const _panel2 = Color(0xFF171D31);
  static const _border = Color(0xFF303A60);
  static const _blue = Color(0xFF29A8FF);
  static const _purple = Color(0xFFA970FF);
  static const _green = Color(0xFF43E08D);
  static const _amber = Color(0xFFFFC857);
  static const _red = Color(0xFFFF6B7A);
  static const _text = Color(0xFFF4F7FF);
  static const _subtle = Color(0xFFA9B4D2);

  Future<GeneratedReportImage> generate(
    OptimizationReport report, {
    ReportImageFormat format = ReportImageFormat.full,
  }) async {
    final size = format == ReportImageFormat.full
        ? const Size(1080, 1920)
        : const Size(1080, 1350);
    final recorder = ui.PictureRecorder();
    final canvas = Canvas(recorder);
    _paintBackground(canvas, size);
    if (format == ReportImageFormat.full) {
      _paintFull(canvas, size, report);
    } else {
      _paintSummary(canvas, size, report);
    }
    final picture = recorder.endRecording();
    final image = await picture.toImage(size.width.toInt(), size.height.toInt());
    final data = await image.toByteData(format: ui.ImageByteFormat.png);
    image.dispose();
    if (data == null) throw Exception('Could not encode report image');
    final bytes = data.buffer.asUint8List();

    final dir = await getApplicationDocumentsDirectory();
    final reportsDir = Directory('${dir.path}/MechOS Reports');
    await reportsDir.create(recursive: true);
    final safeId = report.reportId.replaceAll(RegExp(r'[^A-Za-z0-9_-]'), '_');
    final suffix = format == ReportImageFormat.full ? 'full' : 'summary';
    final path = '${reportsDir.path}/MechOS_Optimization_${safeId}_$suffix.png';
    await File(path).writeAsBytes(bytes, flush: true);
    return GeneratedReportImage(bytes: bytes, path: path, format: format);
  }

  void _paintBackground(Canvas canvas, Size size) {
    canvas.drawRect(Offset.zero & size, Paint()..color = _bg);
    final glow = Paint()
      ..shader = const RadialGradient(
        colors: [Color(0x3329A8FF), Color(0x00111828)],
      ).createShader(Rect.fromCircle(center: Offset(size.width * .15, size.height * .08), radius: 520));
    canvas.drawRect(Offset.zero & size, glow);
    final glow2 = Paint()
      ..shader = const RadialGradient(
        colors: [Color(0x28A970FF), Color(0x00111828)],
      ).createShader(Rect.fromCircle(center: Offset(size.width * .9, size.height * .72), radius: 620));
    canvas.drawRect(Offset.zero & size, glow2);
    final grid = Paint()..color = const Color(0x1129A8FF)..strokeWidth = 1;
    for (double x = 0; x < size.width; x += 54) {
      canvas.drawLine(Offset(x, 0), Offset(x, size.height), grid);
    }
    for (double y = 0; y < size.height; y += 54) {
      canvas.drawLine(Offset(0, y), Offset(size.width, y), grid);
    }
  }

  void _paintHeader(Canvas canvas, OptimizationReport r, double top) {
    _textAt(canvas, 'MECHOS', const Offset(64, 56), 52, FontWeight.w900, _text, letterSpacing: 8);
    _textAt(canvas, 'OPTIMIZATION REPORT', const Offset(66, 120), 25, FontWeight.w800, _blue, letterSpacing: 3);
    _textAt(canvas, 'Generated by MechOS Companion Mobile', const Offset(66, 164), 20, FontWeight.w500, _subtle);
    _badge(canvas, const Rect.fromLTWH(808, 68, 206, 56), '${r.score}/100', _scoreColor(r.score));
    canvas.drawLine(Offset(64, top), Offset(1016, top), Paint()..color = _border..strokeWidth = 2);
  }

  void _paintFull(Canvas canvas, Size size, OptimizationReport r) {
    _paintHeader(canvas, r, 214);
    _sectionTitle(canvas, 'SYSTEM', 252);
    _panelRect(canvas, const Rect.fromLTWH(54, 296, 972, 250));
    _kv(canvas, 'Device', r.hostname, 80, 330);
    _kv(canvas, 'Version', r.osVersion, 80, 378);
    _kv(canvas, 'Build Channel', r.buildChannel, 80, 426);
    _kv(canvas, 'Session', r.session, 80, 474);
    _kv(canvas, 'RadarAI', r.radarAiState, 570, 330, valueColor: _radarColor(r.radarAiState));
    _kv(canvas, 'Report ID', r.reportId, 570, 378);
    _kv(canvas, 'Generated', _date(r.generatedAt), 570, 426);
    _kv(canvas, 'Update', r.updateAvailable ? 'Available' : 'Up to date', 570, 474,
        valueColor: r.updateAvailable ? _amber : _green);

    _sectionTitle(canvas, 'PERFORMANCE', 594);
    final metrics = [
      ('CPU', r.cpuPercent, r.cpuName),
      ('GPU', r.gpuPercent ?? 0, r.gpuPercent == null ? 'Usage unavailable' : r.gpuName),
      ('RAM', r.ramPercent, '${r.ramUsedGb.toStringAsFixed(1)} / ${r.ramTotalGb.toStringAsFixed(0)} GB'),
      ('STORAGE', r.storagePercent, '${r.storageUsedGb.toStringAsFixed(0)} / ${r.storageTotalGb.toStringAsFixed(0)} GB'),
    ];
    for (var i = 0; i < metrics.length; i++) {
      final x = 54.0 + i * 243.0;
      _metricCard(canvas, Rect.fromLTWH(x, 638, 228, 232), metrics[i].$1, metrics[i].$2, metrics[i].$3);
    }

    if (r.temperatureC != null) {
      _textAt(canvas, 'Temperature: ${r.temperatureC!.toStringAsFixed(0)}°C', const Offset(64, 894), 22,
          FontWeight.w700, r.temperatureC! >= 90 ? _red : r.temperatureC! >= 80 ? _amber : _subtle);
    }

    _sectionTitle(canvas, 'TOP FINDINGS', 950);
    _panelRect(canvas, const Rect.fromLTWH(54, 994, 972, 348));
    final findings = r.findings.take(4).toList();
    if (findings.isEmpty) {
      _textAt(canvas, 'No optimization warnings were detected.', const Offset(82, 1040), 25, FontWeight.w700, _green);
    } else {
      for (var i = 0; i < findings.length; i++) {
        final f = findings[i];
        final y = 1032.0 + i * 72;
        final c = _severityColor(f.severity);
        canvas.drawCircle(Offset(84, y + 11), 8, Paint()..color = c);
        _textAt(canvas, f.title, Offset(108, y - 5), 23, FontWeight.w800, _text, maxWidth: 850);
        _textAt(canvas, f.detail, Offset(108, y + 26), 17, FontWeight.w500, _subtle, maxWidth: 850, maxLines: 1);
      }
    }

    _sectionTitle(canvas, 'RECOMMENDED FIXES', 1386);
    _panelRect(canvas, const Rect.fromLTWH(54, 1430, 972, 322));
    final fixes = r.recommendedFixes.take(5).toList();
    if (fixes.isEmpty) fixes.add('No action is required at this time.');
    for (var i = 0; i < fixes.length; i++) {
      final y = 1464.0 + i * 52;
      _textAt(canvas, '✓', Offset(82, y), 22, FontWeight.w900, _green);
      _textAt(canvas, fixes[i], Offset(118, y), 20, FontWeight.w600, _text, maxWidth: 850, maxLines: 1);
    }

    _footer(canvas, size, r);
  }

  void _paintSummary(Canvas canvas, Size size, OptimizationReport r) {
    _paintHeader(canvas, r, 214);
    _sectionTitle(canvas, 'QUICK SUMMARY', 252);
    _panelRect(canvas, const Rect.fromLTWH(54, 296, 972, 224));
    _kv(canvas, 'Device', r.hostname, 80, 330);
    _kv(canvas, 'Version', r.osVersion, 80, 378);
    _kv(canvas, 'Session', r.session, 80, 426);
    _kv(canvas, 'RadarAI', r.radarAiState, 570, 330, valueColor: _radarColor(r.radarAiState));
    _kv(canvas, 'Report ID', r.reportId, 570, 378);
    _kv(canvas, 'Generated', _date(r.generatedAt), 570, 426);

    _sectionTitle(canvas, 'METRICS', 566);
    final metrics = [
      ('CPU', r.cpuPercent),
      ('GPU', r.gpuPercent ?? 0),
      ('RAM', r.ramPercent),
      ('STORAGE', r.storagePercent),
    ];
    for (var i = 0; i < metrics.length; i++) {
      final x = 54.0 + i * 243.0;
      _metricCard(canvas, Rect.fromLTWH(x, 610, 228, 190), metrics[i].$1, metrics[i].$2, '');
    }

    _sectionTitle(canvas, 'TOP ISSUES', 846);
    _panelRect(canvas, const Rect.fromLTWH(54, 890, 972, 268));
    final findings = r.findings.take(3).toList();
    if (findings.isEmpty) {
      _textAt(canvas, 'No optimization warnings detected.', const Offset(82, 938), 24, FontWeight.w700, _green);
    } else {
      for (var i = 0; i < findings.length; i++) {
        final f = findings[i];
        final y = 930.0 + i * 66;
        canvas.drawCircle(Offset(84, y + 11), 8, Paint()..color = _severityColor(f.severity));
        _textAt(canvas, f.title, Offset(108, y - 4), 22, FontWeight.w800, _text, maxWidth: 850);
        _textAt(canvas, f.detail, Offset(108, y + 26), 17, FontWeight.w500, _subtle, maxWidth: 850, maxLines: 1);
      }
    }
    _footer(canvas, size, r);
  }

  void _metricCard(Canvas canvas, Rect rect, String label, double value, String detail) {
    _panelRect(canvas, rect, color: _panel2);
    _textAt(canvas, label, Offset(rect.left + 20, rect.top + 18), 20, FontWeight.w800, _subtle);
    _textAt(canvas, '${value.clamp(0, 100).toStringAsFixed(0)}%', Offset(rect.left + 20, rect.top + 58), 42,
        FontWeight.w900, _usageColor(value));
    final bar = Rect.fromLTWH(rect.left + 20, rect.top + 120, rect.width - 40, 14);
    canvas.drawRRect(RRect.fromRectAndRadius(bar, const Radius.circular(7)), Paint()..color = const Color(0xFF252C42));
    final w = (bar.width * (value.clamp(0, 100) / 100)).toDouble();
    canvas.drawRRect(RRect.fromRectAndRadius(Rect.fromLTWH(bar.left, bar.top, w, bar.height), const Radius.circular(7)),
        Paint()..color = _usageColor(value));
    if (detail.isNotEmpty) {
      _textAt(canvas, detail, Offset(rect.left + 20, rect.top + 150), 15, FontWeight.w500, _subtle,
          maxWidth: rect.width - 40, maxLines: 2);
    }
  }

  void _sectionTitle(Canvas canvas, String title, double y) {
    _textAt(canvas, title, Offset(58, y), 24, FontWeight.w900, _blue, letterSpacing: 2);
  }

  void _kv(Canvas canvas, String key, String value, double x, double y, {Color? valueColor}) {
    _textAt(canvas, key, Offset(x, y), 17, FontWeight.w600, _subtle, maxWidth: 190);
    _textAt(canvas, value, Offset(x + 150, y), 18, FontWeight.w800, valueColor ?? _text, maxWidth: 280, maxLines: 1);
  }

  void _panelRect(Canvas canvas, Rect rect, {Color color = _panel}) {
    final rr = RRect.fromRectAndRadius(rect, const Radius.circular(22));
    canvas.drawRRect(rr, Paint()..color = color);
    canvas.drawRRect(rr, Paint()..style = PaintingStyle.stroke..strokeWidth = 2..color = _border);
  }

  void _badge(Canvas canvas, Rect rect, String text, Color color) {
    final rr = RRect.fromRectAndRadius(rect, const Radius.circular(18));
    canvas.drawRRect(rr, Paint()..color = color.withAlpha(32));
    canvas.drawRRect(rr, Paint()..style = PaintingStyle.stroke..strokeWidth = 2..color = color);
    _textAt(canvas, text, Offset(rect.left + 28, rect.top + 10), 28, FontWeight.w900, color);
  }

  void _footer(Canvas canvas, Size size, OptimizationReport r) {
    final y = size.height - 118;
    canvas.drawLine(Offset(54, y - 22), Offset(size.width - 54, y - 22), Paint()..color = _border..strokeWidth = 2);
    _textAt(canvas, 'MECHOS COMPANION MOBILE', Offset(58, y), 21, FontWeight.w900, _blue, letterSpacing: 2);
    _textAt(canvas, 'Share-ready diagnostic image • ${r.reportId}', Offset(58, y + 38), 17, FontWeight.w500, _subtle);
  }

  Color _scoreColor(int score) => score >= 85 ? _green : score >= 70 ? _blue : score >= 50 ? _amber : _red;
  Color _usageColor(double value) => value >= 90 ? _red : value >= 80 ? _amber : _blue;
  Color _severityColor(String severity) {
    switch (severity.toLowerCase()) {
      case 'critical':
      case 'error':
        return _red;
      case 'warning':
        return _amber;
      default:
        return _blue;
    }
  }

  Color _radarColor(String state) {
    final s = state.toLowerCase();
    if (s.contains('healthy') || s.contains('no threat') || s.contains('clear')) return _green;
    if (s.contains('unavailable') || s.contains('error')) return _red;
    return _blue;
  }

  String _date(DateTime value) {
    final local = value.toLocal();
    String two(int n) => n.toString().padLeft(2, '0');
    return '${local.year}-${two(local.month)}-${two(local.day)} ${two(local.hour)}:${two(local.minute)}';
  }

  void _textAt(
    Canvas canvas,
    String text,
    Offset offset,
    double size,
    FontWeight weight,
    Color color, {
    double maxWidth = 900,
    int maxLines = 2,
    double letterSpacing = 0,
  }) {
    final painter = TextPainter(
      text: TextSpan(
        text: text,
        style: TextStyle(
          color: color,
          fontSize: size,
          fontWeight: weight,
          letterSpacing: letterSpacing,
          height: 1.15,
        ),
      ),
      textDirection: TextDirection.ltr,
      maxLines: maxLines,
      ellipsis: '…',
    )..layout(maxWidth: maxWidth);
    painter.paint(canvas, offset);
  }
}
